### ISSUE TITLE
How to install without composer?

### ISSUE THREAD

**Issue by PabloManuel78** [PagaMasTarde/ordersApiClient#8]
I do not have access to Composer on my server.

I downloaded the library and manually uploaded it to my website.

But I can not find the autoload.php file to be called from PHP with Require_once.

How do I manually upload the API?

**Comment by rmarinleal** [comment]
Hi!
If you don't have composer installed in your server, you can download de latests .phar file of composer and launch the composer-require with ir
```
https://getcomposer.org/composer.phar
```
and put it in the same route of the downloaded library, then run 
```
cd 'path_to_downloaded_library';
php composer.phar require pagamastarde/orders-api-client;
```

If you don't have access to execute php files directly in console you must run it in other local machine and upload the "vendor" directory generated.

**Comment by PabloManuel78** [comment]
Do not you have that "vendor" directory somewhere to download it directly?

**Comment by PabloManuel78** [comment]
I use Plesk, but I do not have access to command line (Shell).

**Comment by PabloManuel78** [comment]
I use Plesk, but I do not have access to command line (Shell).

**Comment by PabloManuel78** [comment]
Solved. The colleagues have already installed the library through the Plesk graphic environment. Thank you!!

**Comment by rmarinleal** [comment]
Perfect! if you have more issues ask us!

**Comment by rmarinleal** [comment]
> Do not you have that "vendor" directory somewhere to download it directly?

The autoload files will be generated with your server paths so you must create them directly in the server or in other similar local machine.

**Comment by rmarinleal** [comment]
> Yes effectively. For those who use Plesk I give you help images, just upload the unzipped folder to your website, either to the root folder or to a subfolder such as "// lib / pagamastarde"
> 
> Through ples in subscription / applications you give to analyze and locate the file composer.json
> 
> In another capture you will see the result in FTP with FileZilla.
> 
> Here you have the official help to use Composer in Plesk without having to use command line (Shell)
> 
> https://docs.plesk.com/es-ES/onyx/administrator-guide/administraci%C3%B3n-de-sitios-web/sitios-web-y-dominios/aplicaciones-web/administraci%C3%B3n-de-las-dependencias-de-proyecto-de-php-con-composer.74969/
> 
> ![2](https://user-images.githubusercontent.com/5701864/47008323-62299200-d13a-11e8-8883-1560a3cbc6cd.JPG)
> ![1](https://user-images.githubusercontent.com/5701864/47008325-62c22880-d13a-11e8-90a5-95445b50505d.JPG)

Thanks for the info ;)
Hope this hep other Plesk users.

**Comment by rmarinleal** [comment]
One tip:

Remember that Paga + Tarde have official modules form e-commerces like magento, prestashop or woocommerce. It you use one of it the module made you all easier ;)

**Comment by PabloManuel78** [comment]
> One tip:
> 
> Remember that Paga + Tarde have official modules form e-commerces like magento, prestashop or woocommerce. It you use one of it the module made you all easier ;)

Yes, we know, they are our competition. I am responsible for the development of the PAGAMÁSTARDE module for our CMS Webforever.

Webforever is a CMS developed in Spain and distributed through SaaS

We hope to launch it in November. Thank you!!
